# Generated by Django 4.2.4 on 2023-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
