# Generated by Django 4.2.4 on 2023-09-09 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messenger", "0002_alter_message_options_alter_room_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="room_participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
