# Generated by Django 4.2.4 on 2023-09-10 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0004_alter_message_options_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
    ]
