# Generated by Django 4.2.4 on 2023-09-10 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messenger", "0006_alter_room_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="room_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
